### ISSUE TITLE
Vuex implementation

### ISSUE THREAD

**Issue by israeleriston** [atomfrede/generator-jhipster-vuejs#2]
What is the possibility of implementing on the jhipster vuex generator ?

**Comment by atomfrede** [comment]
Can you be more specific what you mean? I will reboot this Module after jhipster 4 has been released.

**Comment by israeleriston** [comment]
If you are going to implement vuex (flux architecture) within the generator jhipster and if you need help, I think I can build with some pull requests

**Comment by atomfrede** [comment]
I didn't think about it, but maybe. I can give you a ping when I start

**Comment by israeleriston** [comment]
It will be a pleasure to help the community, I am part of the vuejs-brazil community, the staff here developed a started and made the project available at https://github.com/codecasts/spa-starter-kit with the flux architecture

**Comment by atomfrede** [comment]
Looks great! Thanks for the hint

**Comment by locationguru-git** [comment]
Is ths updated for jhipster 4.2?

**Comment by atomfrede** [comment]
@locationguru-git I didn't update this generator for the latest version, but will try to do it soon, but keep in mind its far from feature complete. If you like and know vue.js feel free to contribute.

**Comment by israeleriston** [comment]
@atomfrede if you update it project, is very very easy do to contributor with the project

**Comment by atomfrede** [comment]
@israeleriston I will try to update it soon. Still waiting for more progress in our react support to see what can be reused here, but maybe I will start with not supporting all features and combinations possible with jhipster

**Comment by israeleriston** [comment]
@atomfrede  very good! but still awaiting your feedback do to contribute project

**Comment by atomfrede** [comment]
Of course contributions are highly welcome!

**Comment by luokyme** [comment]
Will this project be updated?
